#!/bin/bash -ex

MBED_CORE_LOCATION=$1
BOARDNAMES=(ARDUINO_NANO33BLE)

#always work in /tmp
cd /tmp/

if [ ! -d mbed-os-program ]; then
mbed new mbed-os-program
fi
cd mbed-os-program
# checkout the mbed-os version you prefer
# cd mbed-os && git checkout --track origin/feature-hal-spec-usb-device && cd ..

if [ ! -f gron ]; then
echo "Please copy gron executable here"
exit 1
fi

for BOARDNAME in "${BOARDNAMES[@]}"
do

export ARDUINOCORE=$MBED_CORE_LOCATION/variants/$BOARDNAME/

if [ -d $ARDUINOCORE ]; then
mkdir -p $ARDUINOCORE/libs
fi

mbed target $BOARDNAME
mbed toolchain GCC_ARM
echo -e "#include \"mbed.h\"\nint main() {Thread thd;}" > main.cpp
echo -e "{
	\"macros\": [
		\"MBED_HEAP_STATS_ENABLED=1\",
		\"MBED_STACK_STATS_ENABLED=1\",
		\"MBED_MEM_TRACING_ENABLED=1\",
		],
	\"target_overrides\": {
		\"*\": {
			\"platform.stdio-buffered-serial\": true,
			\"platform.stdio-baud-rate\": 115200,
			\"platform.default-serial-baud-rate\": 115200,
		}
	}
}" > mbed_app.json

if [ $BOARDNAME == "ARDUINO_NANO33BLE" ]; then
echo -e "{
	\"macros\": [
		\"MBED_HEAP_STATS_ENABLED=1\",
		\"MBED_STACK_STATS_ENABLED=1\",
		\"MBED_MEM_TRACING_ENABLED=1\",
		\"NRFX_GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS=8\"
		],
	\"target_overrides\": {
		\"*\": {
			\"platform.stdio-buffered-serial\": true,
			\"platform.stdio-baud-rate\": 115200,
			\"platform.default-serial-baud-rate\": 115200,
			\"rtos.main-thread-stack-size\": 32768,
			\"target.mbed_app_start\": \"0x10000\"
		}
	}
}" > mbed_app.json
fi

rm -rf BUILD

mbed compile --source . --source ./mbed-os/features/unsupported/dsp/ -v | grep "Macros:" > $BOARDNAME.macros.txt
cat $BOARDNAME.macros.txt | cut -f2 -d":" | sed 's# #\n#g' | sed 's#\"#\\"#g' | sort > $ARDUINOCORE/defines.txt
echo "-DMBED_NO_GLOBAL_USING_DIRECTIVE=1" >> $ARDUINOCORE/defines.txt
xargs -n 1 < ./BUILD/$BOARDNAME/GCC_ARM/.include* | sed -e 's#-I./mbed-os#-iwithprefixbefore/mbed#g' | sed '/^-I./ d' | tac  > $ARDUINOCORE/includes.txt

./gron ./BUILD/$BOARDNAME/GCC_ARM/.profile-c | grep json.flags | cut -f2 -d"\"" | grep -v "json.flags" | grep -v "MMD" > $ARDUINOCORE/cflags.txt
./gron ./BUILD/$BOARDNAME/GCC_ARM/.profile-cxx | grep json.flags | cut -f2 -d"\"" | grep -v "json.flags" | grep -v "MMD" > $ARDUINOCORE/cxxflags.txt
./gron ./BUILD/$BOARDNAME/GCC_ARM/.profile-ld | grep json.flags | cut -f2 -d"\"" | grep -v "json.flags" | grep -v "MMD" > $ARDUINOCORE/ldflags.txt

arm-none-eabi-ar rcs BUILD/mbed-core-$BOARDNAME.a `xargs -n 1 < ./BUILD/$BOARDNAME/GCC_ARM/.link_options.txt | grep "\.o" | grep -v "/main\.o"`
cp BUILD/mbed-core-$BOARDNAME.a $ARDUINOCORE/libs/libmbed.a
cp ./BUILD/$BOARDNAME/GCC_ARM/.link_script.ld $ARDUINOCORE/linker_script.ld
cp ./BUILD/$BOARDNAME/GCC_ARM/mbed_config.h $ARDUINOCORE/

done

rm -rf $ARDUINOCORE/../../cores/arduino/mbed/*
cd mbed-os && find . | grep "\.h" | xargs -I % cp --parents % $ARDUINOCORE/../../cores/arduino/mbed && cd ..
cp mbed-os/platform/cxxsupport/mstd_* $ARDUINOCORE/../../cores/arduino/mbed/platform/cxxsupport/

#TODO: add #include "mbed_config.h" in "mbed.h"
mv $ARDUINOCORE/../../cores/arduino/mbed/drivers/SPI.h $ARDUINOCORE/../../cores/arduino/mbed/drivers/SPIMaster.h
sed -i 's#drivers/SPI.h#drivers/SPIMaster.h#g' cores/arduino/mbed/mbed.h
sed -i 's?#include "platform/mbed_version.h"?#include "platform/mbed_version.h"\n#include "mbed_config.h"?g' cores/arduino/mbed/mbed.h

# Slim down targets folder, leaving only the used include paths
git add cores/arduino/mbed/targets/
git commit -m "backup commit"
rm -rf cores/arduino/mbed/targets/* | cat variants/*/includes.txt | grep mbed/targets/TARGET_ | sed 's#-iwithprefixbefore#cores/arduino#g' | xargs git checkout
git reset HEAD~1

# - Add -DUSE_ARDUINO_PINOUT to targets with a variant.cpp
for BOARDNAME in "${BOARDNAMES[@]}"
do
if [ -f variants/$BOARDNAME/variant.cpp ]; then
echo "-DUSE_ARDUINO_PINOUT" >> variants/$BOARDNAME/defines.txt
fi
done

exit 0
